// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hywadenfciezcrbcvhjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5d2FkZW5mY2llemNyYmN2aGprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyOTg1ODksImV4cCI6MjA1Njg3NDU4OX0.fIHiU7iH2ByPbagH5cBgGfeOHKE57RMhkH5U9Tb5fUI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});